### ISSUE TITLE
URL needs updating

### ISSUE THREAD

**Issue by kraftbj** [beaulebens/keyring#114]
http://dentedreality.com.au/projects/wp-keyring/ in the readme.txt is redirecting to https://pwd.com.au/blog/

**Comment by freibergergarcia** [comment]
In the meanwhile, you can still access [Web Archive](https://web.archive.org/web/20231203143536/https://dentedreality.com.au/projects/wp-keyring/implementing-keyring-in-your-plugintheme/)

**Comment by beaulebens** [comment]
Ugh, annoying -- I unfortunately lost control of that domain, so it's now at https://beaulebens.com/projects/wp-keyring/

**Comment by beaulebens** [comment]
Closed in https://github.com/beaulebens/keyring/commit/74b0f3cb98628d3946a4cd0ffdadc91c7665c0f4
