### ISSUE TITLE
Use service name in Twitter service

### ISSUE THREAD

**Issue by JJJ** [beaulebens/keyring#15]
In `build_token_meta()`, the Twitter service passes a hardcoded `twitter` parameter into `apply_filters()`. This means when you try to extend this class, you need to create a custom `build_token_meta()` method just to override that string.

**Comment by JJJ** [comment]
I may have found another place this same approach can be employed.

@beaulebens - Is it OK to submit more commits here, or would you prefer new issues for each?

**Comment by beaulebens** [comment]
Fine to do it all here. I'll probably take this and do similar across all the other services before merging anyway.

**Comment by JJJ** [comment]
Done in 8a480071d3eec2b60684ef0d728937b9efe1dd00
