### ISSUE TITLE
"There was a problem authorizing with Eventbrite"

### ISSUE THREAD

**Issue by adamsoffer** [beaulebens/keyring#23]
![image](https://user-images.githubusercontent.com/555740/30117455-4153bb5e-92ee-11e7-80e3-94308c3ddd66.png)

I'm getting this error when trying to authorize eventbrite. The api key and secret are definitely correct. Any idea what's going on here?

**Comment by ads1018** [comment]
I suspect this is an issue related to ssl. I'm making a request from https

**Comment by beaulebens** [comment]
I've confirmed that the Eventbrite service works for me over https, so I'm closing this unless there's more info to help debug.
