### ISSUE TITLE
Adding a Strava service 

### ISSUE THREAD

**Issue by mdrovdahl** [beaulebens/keyring#25]
Just FYI that I'm working on adding Strava support for keyring and also an importer for keyring-social-importers

https://github.com/mdrovdahl/keyring
https://github.com/mdrovdahl/keyring-social-importers

Hoping to have some PR's for you in the coming weeks =)

**Comment by mdrovdahl** [comment]
Ref https://github.com/beaulebens/keyring/pull/26

**Comment by beaulebens** [comment]
Closed in #26
