### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by johnbillion** [beaulebens/keyring#28]
I'd like to use Keyring as a Composer dependency. Currently this means using Wpackagist which isn't ideal.

Would you mind adding a composer.json file and adding the plugin to Packagist?

**Comment by beaulebens** [comment]
I'll see what I can get set up, thanks for the suggestion!

**Comment by beaulebens** [comment]
Done, please LMK if that works; I don't currently have any real projects to test in, so am not sure if I did that right. https://packagist.org/packages/beaulebens/keyring
