### ISSUE TITLE
Microsoft Azure AD support

### ISSUE THREAD

**Issue by ShutterQuick** [beaulebens/keyring#3]
Hi,

This plugin looks great!
Would it be hard to add support for Azure AD?
http://msdn.microsoft.com/en-us/library/azure/dn645545.aspx

I tried modifying one of the existing providers but couldn't make it work. I have zero experience OAuth or wordpress plugins for that matter, so I wasn't able to make it work.

**Comment by beaulebens** [comment]
Closing as abandoned for now.
