### ISSUE TITLE
Cannot get service initialized

### ISSUE THREAD

**Issue by larsemil** [beaulebens/keyring#30]
Hello and happy new years. 
I am trying to implement a service but it does not load as I was hoping. I have followed the documentation [here](https://dentedreality.com.au/projects/wp-keyring/services/).

This is how it looks: 

plugin.php
```
require(__DIR__.'/keyring_services/my_service.php');
add_action('init', 'my_plugin_initialize_service');
```
my_service.php
```
function my_plugin_initialize_service(){
    var_dump('runs');
    class My_Service extends Keyring_Service_GoogleContacts {
       // class code here
   }
}

add_action( 'keyring_load_services', function () {
    var_dump('does not run');
		My_Service::init();
} );
```
`keyring_load_services` seems to be running before `init` and hence it will never initialize.  Do you have an example of keyring being used in a plugin somewhere? 

I have tried wrapping both class declaration and `My_Service::init()` directly in the `keyring_load_services` hook and that does not work. Then the var_dumps run but my service still does not show up. 

Again - happy new year.

What am I doing wrong?

**Comment by larsemil** [comment]
Nevermind. I got it working. I was missing the `keyring_my-service_manage_ui` filter. 
Should be better documented maybe. :)

**Comment by beaulebens** [comment]
> Nevermind. I got it working. I was missing the `keyring_my-service_manage_ui` filter.
> Should be better documented maybe. :)

Glad you got it working, and sorry I didn't get back to you earlier!

Do you mind posting a quick sample of the bit you were missing? I'm definitely happy to update the docs to help others avoid. Cheers.

**Comment by larsemil** [comment]
Yes sure. 
First I did not add a constructor, because on first look it looked like all the info I needed in my service was the same as the parent service I was extending. 
Then I added the same constructor as in `Keyring_Service_GoogleContacts` and nothing happened. After digging around in the code of Keyring I realised i needed to change the name of the hook for UI. 
So the code I ended up with was this: 
```
function __construct() {
			parent::__construct();

			// Enable "basic" UI for entering key/secret
			if ( ! KEYRING__HEADLESS_MODE ) {
				add_action( 'keyring_my-service_manage_ui', array( $this, 'basic_ui' ) );
				add_filter( 'keyring_my-service_basic_ui_intro', array( $this, 'basic_ui_intro' ) );
			}

			// Set scope
			add_filter( 'keyring_my-service_request_token_params', array( $this, 'request_token_params' ) );

			// Handle Google's annoying limitation of not allowing us to redirect to a dynamic URL
			add_action( 'pre_keyring_my-service_verify', array( $this, 'redirect_incoming_verify' ) );

			$this->set_endpoint( 'authorize',    'https://accounts.google.com/o/oauth2/auth',     'GET'  );
			$this->set_endpoint( 'access_token', 'https://accounts.google.com/o/oauth2/token',    'POST' );
			$this->set_endpoint( 'self',         'https://www.googleapis.com/oauth2/v1/userinfo', 'GET'  );

			$creds = $this->get_credentials();
			$this->redirect_uri = $creds['redirect_uri'];
			$this->key          = $creds['key'];
			$this->secret       = $creds['secret'];

			$this->authorization_header    = 'Bearer'; // Oh, you
			$this->authorization_parameter = false;

			// Need to reset the callback because Google is very strict about where it sends people
			if ( !empty( $creds['redirect_uri'] ) ) {
				$this->callback_url = $creds['redirect_uri']; // Allow user to manually enter a redirect URI
			} else {
				$this->callback_url = remove_query_arg( array( 'nonce', 'kr_nonce' ), $this->callback_url ); // At least strip nonces, since you can't save them in your app config
			}
		}
```

I was actually thinking that to do a PR to change the name from:


```
add_action( 'keyring_google-contacts_manage_ui', array( $this, 'basic_ui' ) );

```

into 


```
add_action( 'keyring_'.self::NAME.'_manage_ui', array( $this, 'basic_ui' ) );

```

because it would make extending the class SO much easier.
