### ISSUE TITLE
The token is_expired() method never returns true

### ISSUE THREAD

**Issue by superbia** [beaulebens/keyring#36]
Tokens don't appear to be refreshing when I use Keyring with the google services. Looking at the [is_expired()](https://github.com/beaulebens/keyring/blob/master/token.php#L96) method I think this is because `strtotime` is used on the `expires` meta from the token. Both the google and fitbit services that need to be refreshed return a unix timestamp for the expires value. Running this through `strtotime` gives unpredictable results, with dates far in the future or past.

This could be fixed by simply removing the call to `strtotime` or alternatively testing if `expires` looks like a timestamp and then prefixing `@` to it so `strtotime` knows the string is a timestamp.

I've created a [branch with some tests](https://github.com/superbia/keyring/tree/fix-is-expired) and would be happy to submit a pull request with your desired fix.

**Comment by beaulebens** [comment]
Thanks for spotting that! I looked through all current services and decided to just remove the `strototime`, because in every current instance, that value is saved as a UNIX timestamp.
