### ISSUE TITLE
Creating a second Google service connection causes an 'Undefined index' error

### ISSUE THREAD

**Issue by kbrown9** [beaulebens/keyring#38]
### Steps to reproduce:

1. Make sure that the debug log is enabled ( define( 'WP_DEBUG_LOG', true ); in wp-config.php )

2. Set up a Gmail service connection in the Keyring plugin.

3. Create a second Gmail service connection.

     a) Click 'Add New'.
     b) Click 'Google Mail'.
     c) A new connection should be added to the connections table.
     d) Click 'Show' in the Meta column of the top Google Mail service connection. Notice that the refresh token entry is empty.
     e) Open the debug.log to see the error: "PHP Notice:  Undefined index: refresh_token in /plugins/keyring/includes/services/extended/0-google-base.php on line 110"

It appears the the Google API will only send the refresh token once. So, the second connection is missing the refresh token. 

I don't know why a second service connection would ever be necessary, but it would probably be good to prevent this error.

**Comment by beaulebens** [comment]
Fixed in 4dd9dba301ae5ac4c88a77667002b9433e6d1fe4

**Comment by beaulebens** [comment]
Thanks for finding this, and for the proposed solution! I ended up just forcing things so that all requests require consent, and will thus return a refresh token.
