### ISSUE TITLE
Setting other scopes for Google Mail service

### ISSUE THREAD

**Issue by alperakgun** [beaulebens/keyring#40]
Is it possible to use custom scopes for Gmail keyring service?
https://developers.google.com/gmail/api/auth/scopes

I would like to use: https://www.googleapis.com/auth/gmail.labels

**Comment by beaulebens** [comment]
`Keyring_Service_GoogleMail` extends `Keyring_Service_GoogleBase`, which sets scope on the request token via [the `'keyring_' . $this->get_name() . '_request_token_params'` filter](https://github.com/beaulebens/keyring/blob/master/includes/services/extended/0-google-base.php#L46), so, you should be able to just add your own filter there, and modify the scope to whatever you like.

**Comment by alperakgun** [comment]
Thank you very much!
