### ISSUE TITLE
Test changes to Strava oAuth tokens

### ISSUE THREAD

**Issue by mdrovdahl** [beaulebens/keyring#43]
I haven't investigated this yet- just saw an email referencing it- but, it looks like changes to Strava's oAuth tokens _may_ require refactoring of the Strava service.

Refs: 

* https://developers.strava.com/docs/oauth-updates/
* https://developers.strava.com/docs/oauth-updates/#migration-instructions

**Comment by mdrovdahl** [comment]
Yeah, seems like it broke as announced on Oct 15, 2019 =(

> {"message":"Authorization Error","errors":[{"resource":"Athlete","field":"access_token","code":"invalid"}]}

**Comment by mdrovdahl** [comment]
Need to migrate the Strava service to use short-lived access tokens, refresh tokens and authorization scopes...

**Comment by beaulebens** [comment]
From my manual testing, the changes implemented in 31d71527a05b1c575876f82d664b39bc5a3b66e9 allow you to get a new token, along with refresh details, and also should handle automatically refreshing that token over time (only tested so far with a single refresh period). I mostly just re-used refresh-token handling from the Google services, so at some point it might make sense to abstract out that handling as well.
