### ISSUE TITLE
LinkedIn: Changes to `expires_in` value

### ISSUE THREAD

**Issue by beaulebens** [beaulebens/keyring#64]
Just got an email from LinkedIn about a change in how they send the `expires_in` value that probably should be checked/confirmed to make sure it's not going to impact tokens;

> Dear LinkedIn API Developers,
When retrieving the access token response, your application is currently receiving the expires_in value in milliseconds instead of seconds, as documented. We will correct this issue on 04/06/2020.
Action required
If your application is using the expires_in value, please ensure your references interpret this value in seconds.
We apologize for any inconvenience.

Includes a link to https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow#access-token-response

**Comment by beaulebens** [comment]
cc @glendaviesnz / @pento since this will potentially impact the work you're doing as well I believe.

**Comment by pento** [comment]
Thanks for the heads up, @beaulebens.

I had a look through WPCOM, and everywhere `expires_in` is used, it's assumed to be in seconds: I don't see any special handling for LinkedIn.

**Comment by beaulebens** [comment]
Closing as not relevant any more. I think this applies any more.
