### ISSUE TITLE
Release a new version with the latest fixes

### ISSUE THREAD

**Issue by moon0326** [beaulebens/keyring#76]
Hello,

I've encountered unexpected behavior while testing Google Mail service. `Keyring_Service::requests` considers status code 204 as an error and returns `Keyring_Error`. It looks like the bug has been fixed by https://github.com/beaulebens/keyring/pull/68

Could you please release a new version with the fix to wordpress.org?

Thanks!
Moon

**Comment by beaulebens** [comment]
Done in https://github.com/beaulebens/keyring/releases/tag/v3.0
