### ISSUE TITLE
Delete and Test buttons are not visible in Keyring's Admin UI (Service Connections)

### ISSUE THREAD

**Issue by felipead** [beaulebens/keyring#79]
I was using the latest Keyring version from the official WordPress plugin repository. However, this version is not compatible with WordPress 5.4.2 (it requires <= 5.2.7). As pointed in #77, a fix consists of downloading from GitHub, as compatibility issues have been fixed on master. It worked as expected, and there are no more compatibility issues.

However, I noticed a small UI glitch in the Keyring Admin UI. If you go to the Admin UI (_Tool_ → _Keyring_), add a new service connection (in my case, Google Mail), you can see the service connection details displayed in a table. This table displays some information, such as service name, avatar, external ID, name and OAuth details. The last column has two action links: _Delete_ and _Test_.

Using latest master, a rendering bug hides the _Delete_ and _Test_ links. You need to hover the mouse somewhere in the table to show them. I have reproduced the problem in the following browsers running on macOS Catalina (10.15.5):

- Safari 13.1.1 
- Chrome 84.0.4147.125

Screenshots are attached.

<img width="1552" alt="Screen Shot 2020-08-13 at 23 06 56" src="https://user-images.githubusercontent.com/946848/90206936-5d2bdd00-ddbb-11ea-9f6a-15080d3ddbcb.png">

<img width="1552" alt="Screen Shot 2020-08-13 at 23 07 03" src="https://user-images.githubusercontent.com/946848/90206985-7d5b9c00-ddbb-11ea-83ce-624ae5924840.png">

**Comment by beaulebens** [comment]
That was intentional, but didn't really add much, so I've removed it, thanks.
