### ISSUE TITLE
Make a new repo 😛

### ISSUE THREAD

**Issue by roborourke** [beaulebens/keyring#8]
~1,000,000 commits!

**Comment by beaulebens** [comment]
Yeah, something weird happened with the import from the WordPress.org plugin repo. I'm not sure how to make a new one and retain the relevant history (for Keyring), but get rid of the rest of it.

Any suggestions?

**Comment by sanmai** [comment]
This isn't a problem to remove empty commits (which most old are, as I saw it), but this will break all signed commits, and make all pull requests a mess. Therefore, this late it might be better to keep all as it is.

For the record, empty commits can be removed like so:
```
git filter-branch --prune-empty --tag-name-filter cat -- --all
```

**Comment by beaulebens** [comment]
Done!
