### ISSUE TITLE
Empty posts from Tripit

### ISSUE THREAD

**Issue by Null-Mind** [beaulebens/keyring#87]
Since I upgraded Wordpress to the latest version I now get 2 new posts every day importing a blank trip from trip it

it simple posts this:

Flew () to ().
Flew () to ().
Flew () to ().
Flew () to ().

Here is an example

http://nullmind.com/2020/11/12/flew/

Any ideas how I can troubleshoot this ? I looked in the trip side and there are no trips

**Comment by beaulebens** [comment]
Huh, that's weird, I'm not seeing that on my site running the latest version.

Do those posts have any post_meta associated with them?

Off the top of my head, I'd guess either you've got some other plugin that's somehow interacting weirdly, or probably more likely the data you're getting back from TripIt contains something new/weird that the plugin isn't expecting -- if you have some data in post_meta (specifically `raw_import_data`) then that will hopefully tell us some more.

If that's not there, then maybe try --
1. delete recent tripit posts that have been imported (including these empty ones)
2. set `KEYRING__DEBUG_MODE` to `true` in your `wp-config.php`
3. manually re-run the importer (Tools > Import > TripIt)
4. see if you can find the raw main API response from TripIt in your server's debug log (it's going to be a big blob of JSON data)
5. paste as much of that data here as you're comfortable with (note that it'll contain your travel history, possible email addresses etc -- remove anything that looks like a token/secret)

**Comment by beaulebens** [comment]
Closing due to no feedback.
