### ISSUE TITLE
The access_token provided is invalid.

### ISSUE THREAD

**Issue by quantumalchemy** [beaulebens/keyring#88]
Hi Great Work ..but
everything works - auth users at instagram /  generates tokens / saves in wp  ok
here is code to reproduce:
$service = 'instagram-basic-display';
$service = Keyring::get_service_by_name( $service );
$sc = $service->is_connected();
$token = current($service->get_tokens());
$service->set_token( $token );
$url = "https://api.instagram.com/v1/users/17841426216740799/media/recent/?count=2";
print_r( $service->request( $url ) );   // ON ERROR

 Always gets  -->
OAuthAccessTokenException", "error_message": "The access_token provided is invalid."}}

**Comment by pablinos** [comment]
That all looks ok apart from the URL. The one I'm using is https://graph.instagram.com/me/media

It needs to be `me` as the token is only valid for a specific Instagram account. I think api.instagram.com is the legacy version of the API and the new one is graph.instagram.com.

Hope that helps!

**Comment by quantumalchemy** [comment]
Thanks! Thats it!
I was using the url api  ref in -> github.com/beaulebens/keyring-social-importers 
as and exmple
