### ISSUE TITLE
PHP Notices

### ISSUE THREAD

**Issue by cedriccharles4** [beaulebens/keyring#89]
Hello there :)

Thank you for your great plugin!

I have a lot of php notices in my debuglog files, all from "Keyring": https://snipboard.io/AytRfU.jpg. If I let the debug on TRUE for a few hours, I have more than 1GB of php notices from the plugin.

Could you please have a look at it :) ?

Thank you in advance,
Cedric

**Comment by beaulebens** [comment]
I've just pushed some changes that should take care of most of these. Check it out and please let me know if you see any others. I'm taking a look through to try and make sure things work with PHP8 as well.
